version: "3.7"

services:
  elasticsearch:
    container_name: elk_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - .docker/data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9300:9200"

  kibana:
    container_name: elk_kibana
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5701:5601"
    depends_on:
      - elasticsearch